apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-practice-deployment
  labels:
    app: kube-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-practice
  template:
    metadata:
      labels:
        app: kube-practice
    spec:
      containers:
      - name: kubernetes-practice
        image: gbahdeyboh/kubernetes-practice:v.1.0
        ports:
        - containerPort: 4500
        env:
        - name: db_username
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: database_connection
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: database_url
          value: mongodb://username:password@mongodb-service:27017
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-practice-service
spec:
  selector:
    app: kube-practice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 4500
      nodePort: 31000
